"""Base Strategy — Abstract strategy interface and signal models."""

from __future__ import annotations

import logging
import pandas as pd
import math
from abc import ABC, abstractmethod
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, field_validator

logger = logging.getLogger(__name__)


class StrategyType(str, Enum):
    """Types of trading strategies."""
    TREND_FOLLOW = "trend_follow"
    MEAN_REVERSION = "mean_reversion"
    MOMENTUM = "momentum"
    MARKET_PROFILE = "market_profile"
    VOLUME_DELTA = "volume_delta"
    WYCKOFF = "wyckoff"
    ICT = "ict"
    SMC = "smc"
    FIBONACCI = "fibonacci"
    REGIME_BASED = "regime_based"
    STATISTICAL_ARBITRAGE = "statistical_arbitrage"
    PAIRS_TRADING = "pairs_trading"


# DEPRECATED — use quant_nanggroe.types.signals instead.
# SignalDirection -> SignalType, SignalStrength already in canonical,
# StrategySignal all fields covered by canonical Signal.
class SignalDirection(str, Enum):
    """Signal direction."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    EXIT = "EXIT"


class SignalStrength(str, Enum):
    """Signal strength level."""
    WEAK = "weak"
    MODERATE = "moderate"
    STRONG = "strong"
    VERY_STRONG = "very_strong"


class SignalAction(str, Enum):
    """Trading signal action."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    EXIT = "EXIT"


class StrategySignal(BaseModel):
    # DEPRECATED — use quant_nanggroe.types.signals.Signal instead.
    """A trading signal generated by a strategy."""
    strategy_name: str = ""
    symbol: str = ""
    direction: SignalDirection = SignalDirection.HOLD
    strength: SignalStrength = SignalStrength.MODERATE
    confidence: float = Field(0.0, ge=0.0, le=1.0)

    @field_validator("confidence", mode="before")
    @classmethod
    def _clamp_confidence(cls, v: Any) -> float:
        # ponytail: clamp nan/inf (strategies sometimes emit NaN early in series)
        try:
            f = float(v)
        except (TypeError, ValueError):
            return 0.0
        if not math.isfinite(f):
            return 0.0
        return max(0.0, min(1.0, f))
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    risk_reward_ratio: float = 0.0
    reasoning: str = ""
    indicators: Dict[str, Any] = Field(default_factory=dict)
    timestamp: str = Field(default_factory=lambda: datetime.now(tz=timezone.utc).isoformat())


class StrategyParameters(BaseModel):
    """Strategy parameters container."""
    params: Dict[str, Any] = Field(default_factory=dict)

    def get(self, key: str, default: Any = None) -> Any:
        return self.params.get(key, default)

    def set(self, key: str, value: Any) -> None:
        self.params[key] = value


class Strategy(ABC):
    """Original Strategy class (now also exposed as BaseStrategy for legacy imports)."""
    """Abstract base class for all trading strategies.

    Every strategy must implement generate_signal() and
    can optionally override validate() and get_parameters().

    Usage::

        class MyStrategy(Strategy):
            name = "my_strategy"

            def generate_signal(self, data: pd.DataFrame, **kwargs) -> StrategySignal:
                ...
    """

    name: str = "base_strategy"
    description: str = ""
    required_indicators: List[str] = []

    def __init__(self, parameters: Optional[StrategyParameters] = None) -> None:
        self._parameters = parameters or StrategyParameters()

    @property
    def parameters(self) -> StrategyParameters:
        return self._parameters

    @abstractmethod
    def generate_signal(self, data: Any, **kwargs) -> StrategySignal:
        """Generate a trading signal from market data.

        Args:
            data: Market data (typically DataFrame with OHLCV).
            **kwargs: Additional context (portfolio, regime, etc.)

        Returns:
            StrategySignal with direction, strength, and levels.
        """
        ...

    def validate(self, data: Any) -> bool:
        """Validate that data contains required indicators.

        Returns:
            True if data is valid for this strategy.
        """
        return True

    def get_parameters(self) -> Dict[str, Any]:
        """Get current strategy parameters."""
        return self._parameters.params

    def calculate_risk_reward(
        self, entry: float, stop_loss: float, take_profit: float, direction: SignalDirection
    ) -> float:
        """Calculate risk/reward ratio."""
        if direction == SignalDirection.BUY:
            risk = entry - stop_loss
            reward = take_profit - entry
        else:
            risk = stop_loss - entry
            reward = entry - take_profit

        if risk <= 0:
            return 0.0
        return round(reward / risk, 2)

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__}(name={self.name})>"


# Legacy BaseStrategy compatible with older tests
class BaseStrategy(ABC):
    """Legacy BaseStrategy providing a simple interface and utility methods.

    Expected by older test suite. Supports name, params, warm‑up tracking,
    data validation, and static technical‑analysis helpers.
    """

    def __init__(self, name: str, params: Optional[Dict[str, Any]] = None):
        self.name = name
        self.params = params or {}
        self.is_warmed_up = False

    @abstractmethod
    def generate_signal(self, data: pd.DataFrame):
        """Generate a trading signal given market data."""
        ...

    @abstractmethod
    def required_columns(self) -> list[str]:
        """Return list of required DataFrame columns."""
        ...

    @abstractmethod
    def warmup_period(self) -> int:
        """Minimum number of rows required before strategy is considered warmed up."""
        ...

    def validate_data(self, data: Optional[pd.DataFrame]) -> bool:
        """Validate incoming DataFrame.

        Returns ``True`` if data contains required columns and meets the warm‑up
        period, otherwise ``False``. Raises ``ValueError`` if required columns
        are missing.
        """
        if data is None or data.empty:
            self.is_warmed_up = False
            return False
        missing = [c for c in self.required_columns() if c not in data.columns]
        if missing:
            raise ValueError("missing required columns")
        if len(data) < self.warmup_period():
            self.is_warmed_up = False
            return False
        self.is_warmed_up = True
        return True

    @staticmethod
    def compute_sma(series: pd.Series, period: int) -> pd.Series:
        return series.rolling(window=period, min_periods=period).mean()

    @staticmethod
    def compute_ema(series: pd.Series, period: int) -> pd.Series:
        return series.ewm(span=period, adjust=False, min_periods=period).mean()

    @staticmethod
    def compute_rsi(series: pd.Series, period: int = 14) -> pd.Series:
        delta = series.diff()
        gain = delta.clip(lower=0)
        loss = (-delta).clip(lower=0)
        avg_gain = gain.ewm(alpha=1.0 / period, min_periods=period, adjust=False).mean()
        avg_loss = loss.ewm(alpha=1.0 / period, min_periods=period, adjust=False).mean()
        rs = avg_gain / (avg_loss + 1e-10)
        return 100.0 - (100.0 / (1.0 + rs))

    @staticmethod
    def compute_atr(high: pd.Series, low: pd.Series, close: pd.Series, period: int = 14) -> pd.Series:
        tr1 = high - low
        tr2 = (high - close.shift(1)).abs()
        tr3 = (low - close.shift(1)).abs()
        tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
        return tr.rolling(window=period, min_periods=period).mean()

    @staticmethod
    def compute_bollinger_bands(series: pd.Series, period: int = 20, num_std: float = 2.0):
        middle = series.rolling(window=period, min_periods=period).mean()
        std = series.rolling(window=period, min_periods=period).std()
        upper = middle + num_std * std
        lower = middle - num_std * std
        return upper, middle, lower

    @staticmethod
    def compute_macd(series: pd.Series, fast: int = 12, slow: int = 26, signal: int = 9):
        fast_ema = series.ewm(span=fast, adjust=False).mean()
        slow_ema = series.ewm(span=slow, adjust=False).mean()
        macd = fast_ema - slow_ema
        sig = macd.ewm(span=signal, adjust=False).mean()
        return macd, sig, macd - sig

    @staticmethod
    def compute_zscore(series: pd.Series, period: int):
        rm = series.rolling(window=period, min_periods=period).mean()
        rs = series.rolling(window=period, min_periods=period).std()
        return (series - rm) / (rs + 1e-10)

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__}(name={self.name}, params={self.params})>"


__all__ = [
    "SignalDirection",
    "SignalStrength",
    "SignalAction",
    "StrategySignal",
    "StrategyParameters",
    "Strategy",
    "BaseStrategy",
    "StrategyType",
]
