"""Base Strategy — Abstract strategy interface and signal models."""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)


class SignalDirection(str, Enum):
    """Signal direction."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    EXIT = "EXIT"


class SignalStrength(str, Enum):
    """Signal strength level."""
    WEAK = "weak"
    MODERATE = "moderate"
    STRONG = "strong"
    VERY_STRONG = "very_strong"


class StrategySignal(BaseModel):
    """A trading signal generated by a strategy."""
    strategy_name: str = ""
    symbol: str = ""
    direction: SignalDirection = SignalDirection.HOLD
    strength: SignalStrength = SignalStrength.MODERATE
    confidence: float = Field(0.0, ge=0.0, le=1.0)
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    risk_reward_ratio: float = 0.0
    reasoning: str = ""
    indicators: Dict[str, Any] = Field(default_factory=dict)
    timestamp: str = Field(default_factory=lambda: datetime.now(tz=timezone.utc).isoformat())


class StrategyParameters(BaseModel):
    """Strategy parameters container."""
    params: Dict[str, Any] = Field(default_factory=dict)

    def get(self, key: str, default: Any = None) -> Any:
        return self.params.get(key, default)

    def set(self, key: str, value: Any) -> None:
        self.params[key] = value


class Strategy(ABC):
    """Abstract base class for all trading strategies.

    Every strategy must implement generate_signal() and
    can optionally override validate() and get_parameters().

    Usage::

        class MyStrategy(Strategy):
            name = "my_strategy"

            def generate_signal(self, data: pd.DataFrame, **kwargs) -> StrategySignal:
                ...
    """

    name: str = "base_strategy"
    description: str = ""
    required_indicators: List[str] = []

    def __init__(self, parameters: Optional[StrategyParameters] = None) -> None:
        self._parameters = parameters or StrategyParameters()

    @property
    def parameters(self) -> StrategyParameters:
        return self._parameters

    @abstractmethod
    def generate_signal(self, data: Any, **kwargs) -> StrategySignal:
        """Generate a trading signal from market data.

        Args:
            data: Market data (typically DataFrame with OHLCV).
            **kwargs: Additional context (portfolio, regime, etc.)

        Returns:
            StrategySignal with direction, strength, and levels.
        """
        ...

    def validate(self, data: Any) -> bool:
        """Validate that data contains required indicators.

        Returns:
            True if data is valid for this strategy.
        """
        return True

    def get_parameters(self) -> Dict[str, Any]:
        """Get current strategy parameters."""
        return self._parameters.params

    def calculate_risk_reward(
        self, entry: float, stop_loss: float, take_profit: float, direction: SignalDirection
    ) -> float:
        """Calculate risk/reward ratio."""
        if direction == SignalDirection.BUY:
            risk = entry - stop_loss
            reward = take_profit - entry
        else:
            risk = stop_loss - entry
            reward = entry - take_profit

        if risk <= 0:
            return 0.0
        return round(reward / risk, 2)

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__}(name={self.name})>"


__all__ = [
    "SignalDirection",
    "SignalStrength",
    "StrategySignal",
    "StrategyParameters",
    "Strategy",
]
