"""Guardian core — orchestrates checks, logs to root, auto-dispatches a fixer.

No mock. Runs checks, writes issue .md to project root, appends guardian.log,
and — on any WARNING/CRITICAL — spawns a coding agent (opencode -> hermes
chat -q) with the issue path. OS is auto-detected so the dispatch command is
correct on Windows / Linux / macOS.
"""

from __future__ import annotations

import logging
import os
import platform
import subprocess
import sys
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

from .checks import CheckResult, Severity, all_checks

logger = logging.getLogger(__name__)

ISSUE_DIRNAME = "guardian_issues"


@dataclass
class GuardianConfig:
    project_root: str = ""           # repo worktree root (where issue .md is written)
    loop_interval_sec: int = 60      # seconds between guard passes
    dispatch_on: List[str] = field(default_factory=lambda: [Severity.CRITICAL, Severity.WARNING])
    max_dispatch_per_run: int = 3    # avoid fork bombs; cap agent spawns per pass
    log_dir: str = ""                # defaults to <root>/logs
    enable_dispatch: bool = True     # set False to only log (dry-run)


def detect_os() -> str:
    s = platform.system().lower()
    if s.startswith("win"):
        return "windows"
    if s == "darwin":
        return "macos"
    return "linux"


# ponytail: prefer opencode, fall back to hermes chat -q, then skip.
def _build_dispatch_cmd(issue_path: str, os_name: str) -> Optional[List[str]]:
    which = shutil_which
    if which("opencode"):
        return ["opencode", "-q", f"Fix the issue described in {issue_path}. "
                "Read it, root-cause, patch the code, verify with a syntax check. "
                "Report what you changed."]
    if which("hermes"):
        # hermes chat -q "<prompt>"  (CLI). Pass path as prompt text.
        return ["hermes", "chat", "-q",
                f"Fix the issue in {issue_path}. Read it, root-cause, patch the code, "
                "verify it compiles. Report the change in <5 lines."]
    return None


def shutil_which(name: str) -> bool:
    from shutil import which
    return which(name) is not None


def _write_issue(root: str, result: CheckResult) -> str:
    issue_dir = Path(root) / ISSUE_DIRNAME
    issue_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    fname = f"{ts}_{result.name}.md"
    path = issue_dir / fname
    body = (
        f"# Guardian Issue: {result.name}\n\n"
        f"- **Severity:** {result.severity}\n"
        f"- **Time (UTC):** {result.timestamp}\n"
        f"- **OK:** {result.ok}\n\n"
        f"## Detail\n\n{result.detail}\n\n"
        f"## Suggested Fix (agent instruction)\n\n{result.hint}\n\n"
        f"## Environment\n\n"
        f"- OS: {detect_os()}\n"
        f"- Project root: {root}\n"
        f"- Generated by QNA Autonomous Guardian (no human in loop).\n"
    )
    path.write_text(body, encoding="utf-8")
    return str(path)


def _append_log(log_path: str, result: CheckResult) -> None:
    try:
        Path(log_path).parent.mkdir(parents=True, exist_ok=True)
        with open(log_path, "a", encoding="utf-8") as f:
            f.write(
                f"{result.timestamp} [{result.severity}] {result.name}: {result.detail}\n"
            )
    except Exception as e:  # never let logging kill the loop
        logger.warning("guardian log write failed: %s", e)


def _dispatch(issue_path: str, os_name: str) -> Optional[str]:
    cmd = _build_dispatch_cmd(issue_path, os_name)
    if cmd is None:
        return "no-coding-agent-found(opencode/hermes)"
    try:
        # Detach: run in background, don't block the guardian loop.
        if os_name == "windows":
            subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                             creationflags=0x00000008)  # DETACHED_PROCESS
        else:
            subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                             start_new_session=True)
        return f"dispatched: {' '.join(cmd[:2])}"
    except Exception as e:
        return f"dispatch-failed: {e}"


class Guardian:
    def __init__(self, config: Optional[GuardianConfig] = None):
        self.cfg = config or GuardianConfig()
        if not self.cfg.project_root:
            self.cfg.project_root = str(Path(__file__).resolve().parents[3])  # repo worktree
        if not self.cfg.log_dir:
            self.cfg.log_dir = os.path.join(self.cfg.project_root, "logs")
        self.os_name = detect_os()
        self.log_path = os.path.join(self.cfg.log_dir, "guardian.log")
        self.run_count = 0
        self.last_results: List[CheckResult] = []
        # dedup: don't re-dispatch the same failing check every tick
        self._recent_dispatched: dict = {}
        self._init_logger()

    def _init_logger(self) -> None:
        try:
            Path(self.log_path).parent.mkdir(parents=True, exist_ok=True)
            fh = logging.FileHandler(self.log_path, encoding="utf-8")
            fh.setFormatter(logging.Formatter("%(asctime)s %(levelname)s %(name)s: %(message)s"))
            logger.addHandler(fh)
        except Exception:
            pass

    def run_once(self) -> List[CheckResult]:
        self.run_count += 1
        results = all_checks(self.cfg.project_root)
        self.last_results = results
        dispatched = 0
        now = time.time()
        for r in results:
            if r.ok:
                continue
            # ALWAYS log + write an issue .md on any failure (independent of dispatch).
            _append_log(self.log_path, r)
            issue_path = _write_issue(self.cfg.project_root, r)
            if not self.cfg.enable_dispatch or r.severity not in self.cfg.dispatch_on:
                continue
            if dispatched >= self.cfg.max_dispatch_per_run:
                break
            # dedup: same check name dispatched within 10 min -> skip
            last = self._recent_dispatched.get(r.name, 0)
            if now - last < 600:
                continue
            outcome = _dispatch(issue_path, self.os_name)
            self._recent_dispatched[r.name] = now
            logger.warning("GUARDIAN dispatch (%s) -> %s | issue=%s", r.name, outcome, issue_path)
            dispatched += 1
        return results

    def summary(self) -> dict:
        fails = [r for r in self.last_results if not r.ok]
        return {
            "run_count": self.run_count,
            "os": self.os_name,
            "total": len(self.last_results),
            "healthy": len(self.last_results) - len(fails),
            "failing": [r.name for r in fails],
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }

    def loop(self, max_iterations: int = 0) -> None:
        """Run forever (or up to max_iterations). Ctrl+C to stop."""
        logger.info("Guardian loop start | os=%s root=%s interval=%ss",
                    self.os_name, self.cfg.project_root, self.cfg.loop_interval_sec)
        it = 0
        try:
            while True:
                self.run_once()
                it += 1
                if max_iterations and it >= max_iterations:
                    break
                time.sleep(self.cfg.loop_interval_sec)
        except KeyboardInterrupt:
            logger.info("Guardian stopped by operator.")


# ── CLI entry ──────────────────────────────────────────────────────
def _main() -> None:
    import argparse
    p = argparse.ArgumentParser(description="QNA Autonomous Guardian")
    p.add_argument("--root", default="", help="Project root (issue .md target)")
    p.add_argument("--interval", type=int, default=60, help="Loop seconds")
    p.add_argument("--once", action="store_true", help="Run a single pass and exit")
    p.add_argument("--no-dispatch", action="store_true", help="Log only, do not spawn agents")
    p.add_argument("--max-iter", type=int, default=0, help="Max loop iterations (0=forever)")
    args = p.parse_args()

    cfg = GuardianConfig(
        project_root=args.root, loop_interval_sec=args.interval,
        enable_dispatch=not args.no_dispatch,
    )
    g = Guardian(cfg)
    if args.once:
        res = g.run_once()
        for r in res:
            mark = "OK " if r.ok else "FAIL"
            print(f"[{mark}] {r.name}: {r.detail}")
        s = g.summary()
        print(f"\nSUMMARY: {s['healthy']}/{s['total']} healthy | failing={s['failing']}")
        sys.exit(0 if not s["failing"] else 1)
    g.loop(max_iterations=args.max_iter)


if __name__ == "__main__":
    _main()
