"""Solution builder (Factory) for the AI-MultiColony organism.

Implements the Factory phase of the organism lifecycle: building
solutions, generating code, and creating services in response
to approved decisions.

The factory supports multiple output types: code artifacts,
configuration files, service definitions, and documentation.
"""

from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, ConfigDict

logger = logging.getLogger(__name__)


# ── Enums ────────────────────────────────────────────────────────────────────


class ArtifactType(str, Enum):
    """Type of built artifact."""
    CODE = "code"
    CONFIG = "config"
    SERVICE = "service"
    DOCUMENTATION = "documentation"
    TEST = "test"
    PIPELINE = "pipeline"
    API_ENDPOINT = "api_endpoint"
    DATABASE_MIGRATION = "database_migration"


class BuildStatus(str, Enum):
    """Status of a build."""
    PENDING = "pending"
    BUILDING = "building"
    COMPLETED = "completed"
    FAILED = "failed"
    VALIDATING = "validating"
    DEPLOYED = "deployed"


# ── Models ───────────────────────────────────────────────────────────────────


class BuildArtifact(BaseModel):
    """A built artifact from the factory."""
    model_config = ConfigDict(frozen=False)

    artifact_id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    artifact_type: ArtifactType = ArtifactType.CODE
    name: str = ""
    description: str = ""
    content: str = ""
    language: str = "python"
    version: str = "1.0.0"
    dependencies: List[str] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class BuildRequest(BaseModel):
    """A request to build a solution."""
    model_config = ConfigDict(frozen=False)

    request_id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    decision_id: str = ""
    signal_id: str = ""
    signal_title: str = ""
    artifact_type: ArtifactType = ArtifactType.CODE
    requirements: List[str] = Field(default_factory=list)
    constraints: Dict[str, Any] = Field(default_factory=dict)
    template: str = ""
    parameters: Dict[str, Any] = Field(default_factory=dict)


class BuildResult(BaseModel):
    """Result from a build operation."""
    model_config = ConfigDict(frozen=False)

    build_id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    request_id: str = ""
    status: BuildStatus = BuildStatus.PENDING
    artifacts: List[BuildArtifact] = Field(default_factory=list)
    errors: List[str] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)
    duration_ms: float = 0.0
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def success(self) -> bool:
        return self.status == BuildStatus.COMPLETED and len(self.artifacts) > 0


# ── Code templates ───────────────────────────────────────────────────────────

CODE_TEMPLATES: Dict[str, str] = {
    "python_module": '''"""{module_name} – Auto-generated module.

{description}
"""

from __future__ import annotations

import logging
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)


class {class_name}:
    """{class_description}"""

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self._config = config or {{}}
        self._initialized = False

    async def initialize(self) -> None:
        """Initialize the module."""
        self._initialized = True
        logger.info("{class_name} initialized")

    async def execute(self, **kwargs: Any) -> Dict[str, Any]:
        """Execute the main logic."""
        if not self._initialized:
            await self.initialize()
        return {{"status": "completed", "data": kwargs}}

    @property
    def is_initialized(self) -> bool:
        return self._initialized
''',

    "api_endpoint": '''"""API endpoint for {endpoint_name}.

{description}
"""

from __future__ import annotations

from typing import Any, Dict, Optional
from pydantic import BaseModel, Field


class {request_model}(BaseModel):
    """Request model for {endpoint_name}."""
    pass


class {response_model}(BaseModel):
    """Response model for {endpoint_name}."""
    status: str = "ok"
    data: Dict[str, Any] = Field(default_factory=dict)


async def {handler_name}(request: {request_model}) -> {response_model}:
    """Handle {endpoint_name} requests."""
    return {response_model}(status="ok", data={{}})
''',

    "config": '''# {config_name} Configuration
# Auto-generated by AI-MultiColony Factory
# Generated: {timestamp}

[general]
name = "{config_name}"
description = "{description}"
version = "1.0.0"
enabled = true

[settings]
# Add custom settings here
debug = false
log_level = "INFO"
''',

    "service": '''"""{service_name} Service – Auto-generated.

{description}
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


class {service_class}:
    """{service_description}"""

    SERVICE_NAME = "{service_name}"
    VERSION = "1.0.0"

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self._config = config or {{}}
        self._running = False

    async def start(self) -> None:
        """Start the service."""
        self._running = True
        logger.info("%s started", self.SERVICE_NAME)

    async def stop(self) -> None:
        """Stop the service."""
        self._running = False
        logger.info("%s stopped", self.SERVICE_NAME)

    async def health_check(self) -> Dict[str, Any]:
        """Check service health."""
        return {{
            "service": self.SERVICE_NAME,
            "running": self._running,
            "version": self.VERSION,
        }}

    @property
    def is_running(self) -> bool:
        return self._running
''',
}


# ── Factory ──────────────────────────────────────────────────────────────────


class SolutionFactory:
    """Builds solutions from approved decisions.

    Generates code artifacts, service definitions, configuration
    files, and documentation based on build requests.

    Usage::

        factory = SolutionFactory()
        request = BuildRequest(
            decision_id="dec-123",
            signal_title="Create monitoring service",
            artifact_type=ArtifactType.SERVICE,
            requirements=["Monitor API health", "Alert on failures"],
        )
        result = await factory.build(request)
    """

    def __init__(self):
        self._build_count: int = 0
        self._builds: List[BuildResult] = []
        self._custom_templates: Dict[str, str] = {}

    def register_template(self, name: str, template: str) -> None:
        """Register a custom code template."""
        self._custom_templates[name] = template

    async def build(self, request: BuildRequest) -> BuildResult:
        """Build a solution from a request.

        Parameters
        ----------
        request:
            Build request with requirements and constraints.

        Returns
        -------
        BuildResult
            Build result with generated artifacts.
        """
        import time
        start = time.monotonic()
        self._build_count += 1

        result = BuildResult(
            request_id=request.request_id,
            status=BuildStatus.BUILDING,
        )

        try:
            # Select template
            template_name = request.template or self._select_template(request.artifact_type)
            template = self._custom_templates.get(template_name) or CODE_TEMPLATES.get(template_name, "")

            if not template:
                result.status = BuildStatus.FAILED
                result.errors.append(f"No template found for '{template_name}'")
                result.duration_ms = (time.monotonic() - start) * 1000
                self._builds.append(result)
                return result

            # Generate artifact
            params = self._prepare_params(request)
            content = self._render_template(template, params)

            artifact = BuildArtifact(
                artifact_type=request.artifact_type,
                name=self._generate_name(request),
                description=f"Auto-generated from decision {request.decision_id}",
                content=content,
                language=self._get_language(request.artifact_type),
                metadata={
                    "decision_id": request.decision_id,
                    "signal_id": request.signal_id,
                    "requirements": request.requirements,
                    "template": template_name,
                },
            )

            # Validate
            result.status = BuildStatus.VALIDATING
            validation_errors = self._validate_artifact(artifact)
            if validation_errors:
                result.warnings.extend(validation_errors)

            result.artifacts.append(artifact)
            result.status = BuildStatus.COMPLETED

        except Exception as e:
            result.status = BuildStatus.FAILED
            result.errors.append(str(e))
            logger.error("Build failed: %s", e)

        result.duration_ms = (time.monotonic() - start) * 1000
        self._builds.append(result)
        return result

    async def build_batch(self, requests: List[BuildRequest]) -> List[BuildResult]:
        """Build multiple solutions."""
        results = []
        for request in requests:
            result = await self.build(request)
            results.append(result)
        return results

    # ── Helpers ─────────────────────────────────────────────────────────

    @staticmethod
    def _select_template(artifact_type: ArtifactType) -> str:
        """Select an appropriate template for the artifact type."""
        template_map = {
            ArtifactType.CODE: "python_module",
            ArtifactType.SERVICE: "service",
            ArtifactType.CONFIG: "config",
            ArtifactType.API_ENDPOINT: "api_endpoint",
            ArtifactType.TEST: "python_module",
            ArtifactType.PIPELINE: "python_module",
            ArtifactType.DOCUMENTATION: "config",
            ArtifactType.DATABASE_MIGRATION: "python_module",
        }
        return template_map.get(artifact_type, "python_module")

    @staticmethod
    def _prepare_params(request: BuildRequest) -> Dict[str, Any]:
        """Prepare template parameters from a build request."""
        title = request.signal_title or "unnamed"
        name_parts = title.replace("-", " ").replace("_", " ").split()
        class_name = "".join(p.capitalize() for p in name_parts) or "GeneratedModule"
        module_name = title.lower().replace(" ", "_").replace("-", "_") or "generated_module"

        return {
            "module_name": module_name,
            "class_name": class_name,
            "class_description": request.signal_title or "Auto-generated class",
            "description": request.signal_title or "Auto-generated by AI-MultiColony",
            "endpoint_name": module_name,
            "request_model": f"{class_name}Request",
            "response_model": f"{class_name}Response",
            "handler_name": f"handle_{module_name}",
            "config_name": class_name,
            "service_name": module_name,
            "service_class": class_name,
            "service_description": request.signal_title or "Auto-generated service",
            "timestamp": datetime.now(timezone.utc).isoformat(),
            **request.parameters,
        }

    @staticmethod
    def _render_template(template: str, params: Dict[str, Any]) -> str:
        """Render a template with parameter substitution."""
        result = template
        for key, value in params.items():
            placeholder = "{" + key + "}"
            result = result.replace(placeholder, str(value))
        return result

    @staticmethod
    def _generate_name(request: BuildRequest) -> str:
        """Generate a name for the artifact."""
        title = request.signal_title or "unnamed"
        return title.lower().replace(" ", "_").replace("-", "_")[:50]

    @staticmethod
    def _get_language(artifact_type: ArtifactType) -> str:
        """Get the programming language for an artifact type."""
        lang_map = {
            ArtifactType.CODE: "python",
            ArtifactType.CONFIG: "ini",
            ArtifactType.SERVICE: "python",
            ArtifactType.API_ENDPOINT: "python",
            ArtifactType.TEST: "python",
            ArtifactType.PIPELINE: "python",
            ArtifactType.DOCUMENTATION: "markdown",
            ArtifactType.DATABASE_MIGRATION: "python",
        }
        return lang_map.get(artifact_type, "text")

    @staticmethod
    def _validate_artifact(artifact: BuildArtifact) -> List[str]:
        """Validate a built artifact."""
        warnings: List[str] = []
        if not artifact.content:
            warnings.append("Empty content")
        if not artifact.name:
            warnings.append("Missing artifact name")
        if len(artifact.content) < 10:
            warnings.append("Content too short (possible template rendering issue)")
        return warnings

    @property
    def stats(self) -> Dict[str, Any]:
        """Factory statistics."""
        total = len(self._builds)
        completed = sum(1 for b in self._builds if b.status == BuildStatus.COMPLETED)
        failed = sum(1 for b in self._builds if b.status == BuildStatus.FAILED)
        return {
            "build_count": self._build_count,
            "total_builds": total,
            "completed": completed,
            "failed": failed,
            "success_rate": completed / max(1, total),
            "templates": list(CODE_TEMPLATES.keys()) + list(self._custom_templates.keys()),
        }
