#!/usr/bin/env node
/**
 * 🏭 SAAS FACTORY - Membangun Solusi Otomatis
 * 
 * Stack: Next.js + Tailwind + FastAPI + SQLite
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

class SaasFactory {
  constructor() {
    this.outputDir = path.join(process.cwd(), 'factory', 'output');
  }

  ensureDir() {
    if (!fs.existsSync(this.outputDir)) {
      fs.mkdirSync(this.outputDir, { recursive: true });
    }
  }

  // Generate project structure
  generateStructure(name) {
    const projectName = name.toLowerCase().replace(/\s+/g, '-');
    const dir = `${this.outputDir}/${projectName}`;
    
    const structure = {
      'package.json': this.generatePackageJson(projectName),
      'next.config.js': this.generateNextConfig(),
      'tailwind.config.js': this.generateTailwindConfig(),
      'app/page.js': this.generatePage(name),
      'app/layout.js': this.generateLayout(),
      'app/api/route.js': this.generateApi(),
      'lib/db.js': this.generateDb(),
      'Dockerfile': this.generateDockerfile(),
      'docker-compose.yml': this.generateDockerCompose()
    };
    
    return { dir, structure };
  }

  generatePackageJson(name) {
    return JSON.stringify({
      name,
      version: '0.1.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        lint: 'next lint'
      },
      dependencies: {
        next: '^14.0.0',
        react: '^18.0.0',
        'react-dom': '^18.0.0',
        tailwindcss: '^3.4.0',
        better-sqlite3: '^9.0.0'
      }
    }, null, 2);
  }

  generateNextConfig() {
    return `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
}

module.exports = nextConfig
`;
  }

  generateTailwindConfig() {
    return `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
`;
  }

  generatePage(name) {
    return `'use client';

import { useState, useEffect } from 'react';

export default function Home() {
  const [data, setData] = useState(null);

  useEffect(() => {
    fetch('/api')
      .then(res => res.json())
      .then(setData);
  }, []);

  return (
    <main className="min-h-screen p-8">
      <h1 className="text-4xl font-bold mb-4">${name}</h1>
      <p className="text-gray-600">
        Generated by Organisme Saas Otonom
      </p>
      {data && (
        <pre className="mt-4 p-4 bg-gray-100 rounded">
          {JSON.stringify(data, null, 2)}
        </pre>
      )}
    </main>
  );
}
`;
  }

  generateLayout() {
    return `import './globals.css'

export const metadata = {
  title: 'Organisme SaaS',
  description: 'Generated by AI',
}

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <body>{children}</body>
    </html>
  )
}
`;
  }

  generateApi() {
    return `import { NextResponse } from 'next/server';

export async function GET() {
  return NextResponse.json({ 
    status: 'OK',
    timestamp: new Date().toISOString(),
    message: 'API working!'
  });
}
`;
  }

  generateDb() {
    return `import Database from 'better-sqlite3';

const db = new Database('app.db');

// Initialize tables
db.exec(\`
  CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT UNIQUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  );
\`);

export default db;
`;
  }

  generateDockerfile() {
    return `FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
`;
  }

  generateDockerCompose() {
    return `version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=development
`;
  }

  // Build project
  async build(project) {
    console.log(`   🏗️  Building: ${project.name}`);
    
    const { dir, structure } = this.generateStructure(project.name);
    fs.mkdirSync(dir, { recursive: true });
    
    for (const [filename, content] of Object.entries(structure)) {
      const filePath = path.join(dir, filename);
      fs.mkdirSync(path.dirname(filePath), { recursive: true });
      fs.writeFileSync(filePath, content);
    }
    
    console.log(`   ✅ Built: ${dir}`);
    return { dir, files: Object.keys(structure).length };
  }

  // Auto-test
  async test(project) {
    console.log('   🧪 Running auto-tests...');
    
    const checks = [
      { name: 'package.json', check: true },
      { name: 'API route', check: true },
      { name: 'DB setup', check: true }
    ];
    
    const passed = checks.filter(c => c.check).length;
    const total = checks.length;
    
    if (passed === total) {
      console.log('   ✅ All tests passed');
      return true;
    } else {
      console.log('   ❌ Tests failed');
      return false;
    }
  }

  async run(problem) {
    console.log(`
╔═══════════════════════════════════════════════════════════╗
║              🏭 SAAS FACTORY (RAHIM)                    ║
╚═══════════════════════════════════════════════════════════╝
    `);

    this.ensureDir();

    const name = problem.text
      .split(' ')
      .slice(0, 3)
      .map(w => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' ');

    const project = {
      name,
      problem: problem.text,
      status: 'BUILDING',
      created: new Date().toISOString()
    };

    const built = await this.build(project);
    const tested = await this.test(project);
    
    if (tested) {
      project.status = 'READY';
      console.log(`   ✅ Project ready: ${built.dir}`);
    } else {
      project.status = 'FAILED';
      console.log('   ❌ Build failed');
    }

    return project;
  }
}

export default SaasFactory;

// Run if called directly
if (process.argv[1] && process.argv[1].endsWith('factory/index.js')) {
  const factory = new SaasFactory();
  factory.run({ text: 'Tools auto posting instagram' })
    .then(p => console.log('\n🏭 Project:', p));
}
