// Edge Function: run-factory
// Takes the top idea_candidate and generates a SaaS project template.
// Stores the generated project metadata in engine_runs.meta and logs the process.

import { serve } from "https://deno.land/std@0.168.0/http/function_handler.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

function generateProjectName(theme: string): string {
  const prefixes = ["Auto", "Smart", "Fast", "Easy", "Quick", "Pro"];
  const suffixes = ["Tool", "App", "Hub", "Platform", "Kit", "Flow"];
  const prefix = prefixes[Math.floor(Math.random() * prefixes.length)];
  const suffix = suffixes[Math.floor(Math.random() * suffixes.length)];
  // Also derive from theme
  const themeWords = theme.split(/\s+/).filter(w => w.length > 3).slice(0, 2).map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join("");
  return `${prefix}${themeWords || suffix}`;
}

function generateTemplate(name: string, theme: string, summary: string) {
  const projectName = name.toLowerCase().replace(/\s+/g, '-');
  return {
    packageJson: JSON.stringify({
      name: projectName,
      version: "0.1.0",
      private: true,
      scripts: { dev: "next dev", build: "next build", start: "next start", lint: "next lint" },
      dependencies: {
        next: "^14.0.0",
        react: "^18.0.0",
        "react-dom": "^18.0.0",
        tailwindcss: "^3.4.0",
      },
    }, null, 2),
    page: `'use client';
import { useState } from 'react';

export default function Home() {
  const [data, setData] = useState(null);
  return (
    <main className="min-h-screen p-8 bg-gray-50">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold mb-4">${name}</h1>
        <p className="text-gray-600 mb-8">${summary || "Generated by Autonomous Organism"}</p>
        <div className="bg-white rounded-lg shadow p-6">
          <h2 className="text-xl font-semibold mb-2">Problem</h2>
          <p className="text-gray-700">${theme}</p>
        </div>
      </div>
    </main>
  );
}`,
    api: `import { NextResponse } from 'next/server';
export async function GET() {
  return NextResponse.json({ status: 'OK', service: '${name}', timestamp: new Date().toISOString() });
}`,
    dockerfile: `FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npm", "run", "dev"]`,
  };
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
    const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const SUPABASE_PUBLISHABLE_KEY = Deno.env.get("SUPABASE_PUBLISHABLE_KEY")!;
    if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY || !SUPABASE_PUBLISHABLE_KEY) {
      throw new Error("Backend secrets not configured");
    }

    const authHeader = req.headers.get("Authorization") ?? "";
    const userClient = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: authHeader } },
    });
    const { data: userData } = await userClient.auth.getUser();
    if (!userData.user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const admin = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
    const { data: profile } = await admin.from("profiles").select("organization_id").eq("user_id", userData.user.id).maybeSingle();
    if (!profile?.organization_id) throw new Error("Profile/org not initialized");
    const orgId = profile.organization_id as string;

    // Create engine run
    const { data: run, error: runErr } = await admin.from("engine_runs").insert({ organization_id: orgId, engine: "factory", status: "running" }).select("id").single();
    if (runErr) throw runErr;
    const runId = run.id as string;

    const log = async (level: string, source: string, message: string) => {
      await admin.from("engine_logs").insert({ organization_id: orgId, run_id: runId, level, source, message });
    };

    await log("system", "FACTORY", "Factory run started");

    // Get top idea candidate
    const { data: ideas, error: ideasErr } = await admin
      .from("idea_candidates")
      .select("id, theme, score, summary")
      .eq("organization_id", orgId)
      .order("score", { ascending: false })
      .limit(1);
    if (ideasErr) throw ideasErr;

    if (!ideas || ideas.length === 0) {
      await log("warning", "FACTORY", "No idea candidates found. Run Decision first.");
      await admin.from("engine_runs").update({ status: "failed", finished_at: new Date().toISOString() }).eq("id", runId);
      return new Response(JSON.stringify({ error: "No ideas to build. Run Decision first." }), { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const topIdea = ideas[0];
    const projectName = generateProjectName(topIdea.theme);
    const template = generateTemplate(projectName, topIdea.theme, topIdea.summary);

    await log("info", "FACTORY", `Generating project: ${projectName} from idea: ${topIdea.theme}`);

    // Try AI-enhanced generation if OPENAI_API_KEY is set
    const aiKey = Deno.env.get("OPENAI_API_KEY");
    const aiModel = Deno.env.get("AI_MODEL") || "gpt-4o-mini";
    let enhancedPage = template.page;
    let aiRaw = "";

    if (aiKey) {
      try {
        const prompt = `Generate a Next.js landing page component for a SaaS product called "${projectName}" that solves: "${topIdea.theme}". Summary: ${topIdea.summary}. Return ONLY the JSX code for the page component (no imports needed besides useState from react). Use Tailwind CSS. Keep it under 100 lines.`;
        const aiResp = await fetch("https://api.openai.com/v1/chat/completions", {
          method: "POST",
          headers: { "Authorization": `Bearer ${aiKey}`, "Content-Type": "application/json" },
          body: JSON.stringify({ model: aiModel, messages: [{ role: "user", content: prompt }], max_tokens: 1000, temperature: 0.7 }),
        });
        const aiJson = await aiResp.json();
        aiRaw = aiJson.choices?.[0]?.message?.content ?? "";
        if (aiRaw) {
          enhancedPage = `'use client';\nimport { useState } from 'react';\n\nexport default function Home() {\n  return (\n${aiRaw}\n  );\n}`;
          await log("success", "FACTORY", "AI-enhanced page generated");
        }
      } catch (e) {
        await log("warning", "FACTORY", `AI generation failed: ${e instanceof Error ? e.message : "unknown"}. Using template fallback.`);
      }
    }

    const project = {
      name: projectName,
      idea_id: topIdea.id,
      theme: topIdea.theme,
      status: "READY",
      files: {
        "package.json": template.packageJson,
        "app/page.js": enhancedPage,
        "app/api/route.js": template.api,
        "Dockerfile": template.dockerfile,
      },
      generated_at: new Date().toISOString(),
      generator: aiKey ? `ai-${aiModel}` : "template",
    };

    await log("success", "FACTORY", `Project ready: ${projectName} (${Object.keys(project.files).length} files)`);

    await admin.from("engine_runs").update({
      status: "success",
      finished_at: new Date().toISOString(),
      meta: project,
    }).eq("id", runId);

    return new Response(JSON.stringify({ ok: true, project }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("run-factory error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
});
