#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════════════╗
# ║      Quant-Nanggroe-AI  —  Environment Hardening Script            ║
# ║      SSH, Firewall, Fail2Ban, Auto-Updates, Security Baseline      ║
# ╚══════════════════════════════════════════════════════════════════════╝
set -euo pipefail

# ── Configuration ──────────────────────────────────────────────────────
SSH_PORT="${SSH_PORT:-22}"
ALLOWED_USERS="${ALLOWED_USERS:-deploy}"
FAIL2BAN_BANTIME="${FAIL2BAN_BANTIME:-3600}"
FAIL2BAN_FINDTIME="${FAIL2BAN_FINDTIME:-600}"
FAIL2BAN_MAXRETRY="${FAIL2BAN_MAXRETRY:-5}"
ADMIN_EMAIL="${ADMIN_EMAIL:-}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log()    { echo -e "${BLUE}[HARDEN]${NC} $*"; }
warn()   { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()    { echo -e "${RED}[ERROR]${NC} $*" >&2; }
success(){ echo -e "${GREEN}[OK]${NC} $*"; }
die()    { err "$*"; exit 1; }

require_root() {
    if [ "$EUID" -ne 0 ]; then
        die "This script must be run as root (use sudo)"
    fi
}

# ── 1. Disable Root SSH Login ─────────────────────────────────────────
harden_ssh() {
    log "═══ Hardening SSH ═══"

    local sshd_config="/etc/ssh/sshd_config"
    local sshd_hardened="/etc/ssh/sshd_config.d/99-qna-hardened.conf"

    mkdir -p /etc/ssh/sshd_config.d

    cat > "$sshd_hardened" <<'EOF'
# Quant-Nanggroe-AI SSH Hardening
# Generated by harden.sh — do not edit manually

# Disable root login
PermitRootLogin no

# Disable password authentication (use keys only)
PasswordAuthentication no
ChallengeResponseAuthentication no
UsePAM no

# Limit SSH to specific users
AllowUsers deploy

# Use SSH protocol 2 only
Protocol 2

# Key exchange algorithms (strong only)
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512

# Ciphers (strong only)
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com

# MACs (strong only)
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com

# Disable empty passwords
PermitEmptyPasswords no

# Disable X11 forwarding
X11Forwarding no

# Disable TCP forwarding (unless needed)
AllowTcpForwarding no

# Disable agent forwarding
AllowAgentForwarding no

# Set login grace time
LoginGraceTime 30

# Max auth tries
MaxAuthTries 3

# Client alive interval (detect idle connections)
ClientAliveInterval 300
ClientAliveCountMax 2

# Disable DNS lookup
UseDNS no

# Log level
LogLevel VERBOSE
EOF

    # Update AllowUsers if custom user specified
    if [ "$ALLOWED_USERS" != "deploy" ]; then
        sed -i "s/AllowUsers deploy/AllowUsers $ALLOWED_USERS/" "$sshd_hardened"
    fi

    # Validate SSH config before applying
    if sshd -t -f "$sshd_config" -C "include=$sshd_hardened" 2>/dev/null; then
        systemctl restart sshd
        success "SSH hardened: root login disabled, key-only auth"
    else
        warn "SSH config validation failed — check $sshd_hardened"
    fi
}

# ── 2. Configure Firewall (UFW) ───────────────────────────────────────
configure_firewall() {
    log "═══ Configuring Firewall (UFW) ═══"

    if ! command -v ufw &>/dev/null; then
        log "Installing UFW..."
        apt-get update -qq && apt-get install -y -qq ufw
    fi

    # Reset to defaults
    ufw --force reset

    # Default policies
    ufw default deny incoming
    ufw default allow outgoing

    # Allow SSH (custom port)
    ufw allow "$SSH_PORT/tcp" comment "SSH"

    # Allow HTTP/HTTPS
    ufw allow 80/tcp comment "HTTP"
    ufw allow 443/tcp comment "HTTPS"

    # Allow application port (if running on this host)
    ufw allow 8000/tcp comment "QNA API"

    # Allow Prometheus (internal only — restrict in production)
    ufw allow from 127.0.0.1 to any port 9090 comment "Prometheus local"
    ufw allow from 127.0.0.1 to any port 3000 comment "Grafana local"

    # Rate limiting on SSH
    ufw limit "$SSH_PORT/tcp" comment "SSH rate limit"

    # Enable firewall
    ufw --force enable

    ufw status verbose
    success "Firewall configured"
}

# ── 3. Set Up Fail2Ban ────────────────────────────────────────────────
configure_fail2ban() {
    log "═══ Configuring Fail2Ban ═══"

    if ! command -v fail2ban-client &>/dev/null; then
        log "Installing Fail2Ban..."
        apt-get update -qq && apt-get install -y -qq fail2ban
    fi

    # Local jail configuration
    cat > /etc/fail2ban/jail.local <<EOF
[DEFAULT]
# Ban duration: 1 hour
bantime = $FAIL2BAN_BANTIME

# Detection window: 10 minutes
findtime = $FAIL2BAN_FINDTIME

# Max retries before ban
maxretry = $FAIL2BAN_MAXRETRY

# Ban action: UFW
banaction = ufw

# Email notifications (if configured)
$(if [ -n "$ADMIN_EMAIL" ]; then
    echo "destemail = $ADMIN_EMAIL"
    echo "sender = fail2ban@\$(hostname)"
    echo "mta = sendmail"
    echo "action = %(action_mwl)s"
else
    echo "action = %(action_)s"
fi)

[sshd]
enabled = true
port = $SSH_PORT
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 7200

[sshd-aggressive]
enabled = true
port = $SSH_PORT
filter = sshd[mode=aggressive]
logpath = /var/log/auth.log
maxretry = 5
bantime = 86400

[qna-api]
enabled = true
port = 8000
filter = qna-api
logpath = /var/log/qna_api_access.log
maxretry = 20
bantime = 3600
findtime = 600
EOF

    # Custom filter for QNA API abuse
    cat > /etc/fail2ban/filter.d/qna-api.conf <<'EOF'
[Definition]
failregex = ^<HOST> .* "(GET|POST|PUT|DELETE) .*" (429|401|403) .*$
ignoreregex =
EOF

    systemctl enable fail2ban
    systemctl restart fail2ban

    success "Fail2Ban configured: SSH + API protection"
}

# ── 4. Automatic Security Updates ─────────────────────────────────────
configure_auto_updates() {
    log "═══ Configuring Automatic Security Updates ═══"

    if ! dpkg -l | grep -q unattended-upgrades; then
        apt-get update -qq && apt-get install -y -qq \
            unattended-upgrades \
            apt-listchanges
    fi

    # Enable unattended upgrades for security only
    cat > /etc/apt/apt.conf.d/20auto-upgrades <<'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
EOF

    # Configure: security updates only
    cat > /etc/apt/apt.conf.d/50unattended-upgrades <<'EOF'
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
};
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot "false";
Unattended-Upgrade::Mail "";
EOF

    # Test the configuration
    unattended-upgrades --dry-run --debug 2>&1 | tail -5

    systemctl enable unattended-upgrades
    systemctl restart unattended-upgrades

    success "Automatic security updates enabled"
}

# ── 5. Additional Security Hardening ───────────────────────────────────
harden_system() {
    log "═══ Additional System Hardening ═══"

    # Restrict cron access
    echo "root" > /etc/cron.allow
    chmod 600 /etc/cron.allow

    # Set proper permissions on sensitive files
    chmod 600 /etc/shadow /etc/gshadow
    chmod 644 /etc/passwd /etc/group

    # Disable core dumps
    echo "* hard core 0" >> /etc/security/limits.conf
    echo "fs.suid_dumpable = 0" >> /etc/sysctl.conf

    # Kernel hardening via sysctl
    cat >> /etc/sysctl.conf <<'EOF'

# Quant-Nanggroe-AI Kernel Hardening
# IP spoofing protection
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Disable ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# Disable source routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0

# SYN flood protection
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.tcp_synack_retries = 2

# Log suspicious packets
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

# Ignore ICMP broadcast requests
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Ignore bogus ICMP errors
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Randomize address space layout
kernel.randomize_va_space = 2
EOF

    sysctl -p 2>/dev/null || warn "Some sysctl settings may not apply in container"

    # Set umask
    echo "umask 027" >> /etc/profile

    success "System hardening complete"
}

# ── 6. Verification ───────────────────────────────────────────────────
verify_hardening() {
    log "═══ Verifying Hardening ═══"
    local all_ok=true

    # Check SSH
    if grep -q "^PermitRootLogin no" /etc/ssh/sshd_config.d/99-qna-hardened.conf 2>/dev/null; then
        success "SSH: root login disabled"
    else
        warn "SSH: root login may still be enabled"
        all_ok=false
    fi

    # Check UFW
    if ufw status | grep -q "Status: active"; then
        success "Firewall: UFW active"
    else
        warn "Firewall: UFW not active"
        all_ok=false
    fi

    # Check Fail2Ban
    if systemctl is-active --quiet fail2ban; then
        success "Fail2Ban: running"
    else
        warn "Fail2Ban: not running"
        all_ok=false
    fi

    # Check auto-updates
    if systemctl is-active --quiet unattended-upgrades; then
        success "Auto-updates: enabled"
    else
        warn "Auto-updates: not enabled"
        all_ok=false
    fi

    if [ "$all_ok" = true ]; then
        success "All hardening checks passed"
    else
        warn "Some checks failed — review output above"
    fi
}

# ── Usage ──────────────────────────────────────────────────────────────
usage() {
    cat <<EOF
Usage: $0 [command]

Commands:
    all         Apply all hardening measures (default)
    ssh         Harden SSH only
    firewall    Configure firewall only
    fail2ban    Set up Fail2Ban only
    updates     Enable auto security updates
    verify      Verify current hardening status
    help        Show this help

Environment Variables:
    SSH_PORT            SSH port (default: 22)
    ALLOWED_USERS       Space-separated list of allowed SSH users
    FAIL2BAN_BANTIME    Ban duration in seconds (default: 3600)
    FAIL2BAN_FINDTIME   Detection window in seconds (default: 600)
    FAIL2BAN_MAXRETRY   Max retries before ban (default: 5)
    ADMIN_EMAIL         Email for security notifications

Examples:
    sudo $0                          # Apply all hardening
    sudo SSH_PORT=2222 $0 ssh        # Harden SSH on custom port
    sudo ADMIN_EMAIL=admin@corp.com $0 all  # With email alerts
    sudo $0 verify                   # Check current status
EOF
}

# ── Main ───────────────────────────────────────────────────────────────
main() {
    local cmd="${1:-all}"

    require_root

    log "Quant Nanggroe AI — Environment Hardening"
    log "Timestamp: $(date -Iseconds)"

    case "$cmd" in
        all)
            harden_ssh
            configure_firewall
            configure_fail2ban
            configure_auto_updates
            harden_system
            verify_hardening
            ;;
        ssh)      harden_ssh ;;
        firewall) configure_firewall ;;
        fail2ban) configure_fail2ban ;;
        updates)  configure_auto_updates ;;
        verify)   verify_hardening ;;
        help|--help|-h) usage ;;
        *)        die "Unknown command: $cmd. Run '$0 help' for usage." ;;
    esac

    success "Hardening complete"
}

main "$@"
