#!/bin/bash
# QNA Cleanup — Archive Zero-Reference Orphan Scripts
# Generated by fangbot audit
# Safe to run: all these files have ZERO imports from inside the package

REPO="/d/repositories/Quant-Nanggroe-AI-worktree"
ARCHIVE="$REPO/archive/old-scripts"

mkdir -p "$ARCHIVE"

FILES=(
  "_fangbot_jobscan.py"
  "_qt_bt.py"
  "_qt_scan.py"
  "_qt_test.py"
  "full_optimizer.py"
  "hedge_fund_mtf.py"
  "hedge_fund_multipair.py"
  "integration_test.py"
  "master_backtest.py"
  "patch_qna_prod.py"
  "production_runner.py"
  "qna-aihf-adapter.py"
  "qna-production-runner.py"
  "sahamid.py"
  "smc_upgrade_backtest.py"
  "strategy_fixes.py"
  "terminal.py"
  "test_fixes.py"
  "test_singleton.py"
  "tradebobby_bridge.py"
  "wyckoff_optimizer.py"
)

echo "=== Moving orphan root .py files to archive/old-scripts/ ==="
for f in "${FILES[@]}"; do
  if [ -f "$REPO/$f" ]; then
    git mv "$REPO/$f" "$ARCHIVE/$f"
    echo "  Moved: $f"
  else
    echo "  SKIP (not found): $f"
  fi
done
