"""API route handlers for all REST endpoints."""

# Package init

__all__ = [
    '_data',
    'agentic',
    'agents',
    'analytics',
    'autonomous',
    'backtest',
    'brokers',
    'channels',
    'colony',
    'council',
    'credentials',
    'debate',
    'ecosystem',
    'fred',
    'market',
    'memory',
    'monitor',
    'options',
    'personas',    'portfolio', 'pipeline_status', 'rl', 'sec_edgar', 'signal_generator',
    'strategies', 'strategy', 'trading', 'whatsapp', 'wiring_compat', 'ws',
]

from . import (
    _data,
    agentic,
    agents,
    analytics,
    autonomous,
    backtest,
    brokers,
    channels,
    colony,
    council,
    credentials,
    debate,
    ecosystem,
    fred,
    market,
    memory,
    monitor,
    options,
    personas,
    pipeline_status,
    portfolio,
    rl,
    sec_edgar,
    signal_generator,
    strategies,
    strategy,
    trading,
    whatsapp,
    wiring_compat,
    ws,
)
