"""API route handlers for all REST endpoints."""

# Package init

__all__ = [
    '_data',
    'agentic',
    'agents',
    'analytics',
    'autonomous',
    'backtest',
    'brokers',
    'channels',
    'colony',
    'config',
    'council',
    'credentials',
    'debate',
    'ecosystem',
    'fred',
    'market',
    'memory',
    'monitor',
    'options',
    'orderbook',
    'personas',
    'pipeline_status',
    'portfolio',
    'rl',
    'sec_edgar',
    'signal_generator',
    'strategies',
    'strategy',
    'trade_history',
    'trading',
    'whatsapp',
    'wiring_compat',
    'ws',
    'otto_proxy',
]

from . import (
    _data,
    agentic,
    agents,
    analytics,
    autonomous,
    backtest,
    brokers,
    channels,
    colony,
    config,
    council,
    credentials,
    debate,
    ecosystem,
    fred,
    market,
    memory,
    monitor,
    options,
    orderbook,
    otto_proxy,
    personas,
    pipeline_status,
    portfolio,
    rl,
    sec_edgar,
    signal_generator,
    strategies,
    strategy,
    trade_history,
    trading,
    whatsapp,
    wiring_compat,
    ws,
)
